[theme]
base = "dark"
primaryColor = "#14b8a6"            # acentos (teal legible en dark)
backgroundColor = "#0b1221"         # fondo principal (azul petróleo muy oscuro)
secondaryBackgroundColor = "#111827"# contenedores/cards
textColor = "#e5e7eb"               # texto gris muy claro
font = "sans serif"
